name: Composite Action Demo

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run custom action
        uses: ./.github/actions/setup-and-greet
        with:
          name: Nilamadhab
          language: en