name: PR Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    


jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Print PR branch name
        run: echo "PR Branch name:" ${{ github.head_ref }}