name: Reusable Build Test

on:
  workflow_call:

    inputs:
      python_version:
        required: true
        type: string

      run_tests:
        required: false
        default: true
        type: boolean

    outputs:
      test_result:
        value: ${{ jobs.build.outputs.test_result }}

jobs:

  build:

    runs-on: ubuntu-latest

    outputs:
      test_result: ${{ steps.result.outputs.status }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - run: pip install -r requirements.txt

      - name: Run tests
        if: inputs.run_tests == true
        run: ./test.sh

      - name: Set result
        id: result
        run: echo "status=passed" >> $GITHUB_OUTPUT